class Move {
  constructor(pos, velocity) {
    this.pos = pos;
    this.velocity = velocity;
  }
  execute() {
    this.pos.x += this.velocity.x;
    this.pos.y += this.velocity.y;
    console.log('Object has been moved, current position: ', this.pos.x, this.pos.y);
  }
}

class IoC {
  constructor() {
    this.registrations = new Map();
    this.scopes = new Map();
    this.currentScope = null;
  }

  resolve(key, ...args) {
    if (key === 'IoC.Register') {
      const [registerKey, factory] = args;
      this.registrations.set(registerKey, factory);

      return;
    }

    if (key === 'Scopes.New') {
      const [scopeId] = args;
      this.scopes.set(scopeId, new Map());

      return;
    }

    if (key === 'Scopes.Current') {
      const [scopeId] = args;

      if (this.scopes.has(scopeId)) {
        this.currentScope = this.scopes.get(scopeId);
      }

      return;
    }

    if (this.currentScope && this.currentScope.has(key)) {
      return this.currentScope.get(key)(...args);
    }

    if (this.registrations.has(key)) {
      const instance = this.registrations.get(key)(...args);
      if (this.currentScope) {
        this.currentScope.set(key, () => instance);
      }
      return instance;
    }
  }
}

class Vector {
  constructor(x, y) {
    this.x = x;
    this.y = y;
  }
}

const ioc = new IoC();

ioc.resolve(
  'IoC.Register',
  'Move',
  () => new Move(new Vector(0, 0), new Vector(1, 0))
);

const moveInstance = ioc.resolve('Move');

ioc.resolve(
  'IoC.Register',
  'Spaceship.Operations.IMovable:getPosition',
  (obj) => new Vector(obj.pos.x, obj.pos.y)
);

ioc.resolve(
  'IoC.Register',
  'Spaceship.Operations.IMovable:getVelocity',
  (obj) => new Vector(obj.velocity.x, obj.velocity.y)
);

ioc.resolve(
  'IoC.Register',
  'Spaceship.Operations.IMovable:setPosition',
  (obj, newValue) => ({
    execute: () => {
      obj.pos.x = newValue.x;
      obj.pos.y = newValue.y;
    },
  })
);

const IMovable = {
  name: 'Spaceship.Operations.IMovable',
  methods: [
    { name: 'getPosition', returnType: 'Vector', args: [] },
    { name: 'setPosition', returnType: 'void', args: ['Vector'] },
    { name: 'getVelocity', returnType: 'Vector', args: [] }
  ]
};

function generateAdapter(interfaceDef) {
  const { name, methods } = interfaceDef;

  return class AutoGeneratedAdapter {
    constructor(obj) {
      this.obj = obj;

      methods.forEach(method => {
        this[method.name] = (...args) => {
          const key = `${name}:${method.name}`;

          const result = ioc.resolve(key, this.obj, ...args);

          if (method.returnType === 'void') {
            if (result && typeof result.execute === 'function') {
              result.execute();
            }
            return;
          }

          return result;
        };
      });
    }
  };
}

ioc.resolve(
  'IoC.Register',
  'Adapter',
  (interfaceDef,obj) => {
    const AdapterClass = generateAdapter(interfaceDef);
    return new AdapterClass(obj)}
);

const adapter = ioc.resolve('Adapter', IMovable, moveInstance);

console.log("init position", adapter.getPosition());

adapter.setPosition(new Vector(20, 20));

console.log("new position", adapter.getPosition());


module.exports = { Move, IoC, Vector, IMovable, ioc };
