name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install root dependencies
      run: npm install

    - name: Install jwt-service dependencies
      run: cd jwt-service && npm install

    - name: Install game-service dependencies
      run: cd game-service && npm install

    - name: Run tests
      run: npm test
